# Generated by Django 2.2.15 on 2021-04-28 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eshopeform',
            name='email',
        ),
        migrations.RemoveField(
            model_name='eshopeform',
            name='messages',
        ),
        migrations.RemoveField(
            model_name='eshopeform',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='eshopeform',
            name='name',
        ),
        migrations.RemoveField(
            model_name='eshopeform',
            name='nature_of_business',
        ),
        migrations.RemoveField(
            model_name='eshopeform',
            name='send_copy',
        ),
    ]
