# Generated by Django 2.2.15 on 2021-04-26 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='add_home',
            field=models.BooleanField(default=False),
        ),
    ]
