# Generated by Django 2.2.15 on 2021-04-21 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, choices=[('prestige', 'Prestige'), ('padmini', 'Padmini'), ('other', 'Other')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='capacity',
            field=models.CharField(blank=True, choices=[('200ml', '200 ml'), ('500ml', '500 ml'), ('1ltr', '1 ltr')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='closure_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='material',
            field=models.CharField(blank=True, choices=[('polycarbonate', 'Polycarbonate'), ('PET', 'PET'), ('other', 'Other')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='min_order_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='model_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='neck_size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='power',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_group',
            field=models.CharField(blank=True, choices=[('Kitchen_stoves', 'Kitchen Stoves'), ('mixture_grinder', 'Mixture Grinder'), ('rice_cookers', 'Rice Cookers'), ('food_processors', 'Food Processors'), ('electric_mixers', 'Electric Mixers'), ('juicers', 'Juicers'), ('blenders', 'Blenders'), ('water_heaters', 'Water Heaters'), ('water_filters', 'Water Filters'), ('induction cookers', 'Induction Cookers'), ('exhaust_hoods', 'Exhaust Hoods'), ('sandwich_makers', 'Sandwich Makers'), ('toaster', 'Toaster'), ('deep_fryers', 'Deep Fryers'), ('dough_blenders', 'Dough Blenders'), ('coffee_makers', 'Coffee Makers'), ('electric_iron', 'Electric Iron'), ('vaccum_cleaner', 'Vaccum Cleaner'), ('air_purifiers', 'Air Purifiers'), ('trimmers_&_savers', 'Trimmer And Savers'), ('hair_drier', 'Hair Drier')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='unity_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='warranty',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
