# Generated by Django 2.2.15 on 2021-04-28 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20210428_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='eshopeform',
            name='email',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eshopeform',
            name='messages',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='eshopeform',
            name='mobile',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eshopeform',
            name='name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eshopeform',
            name='nature_of_business',
            field=models.CharField(choices=[('Manufacturer', 'Manufacturer'), ('Retailer', 'Retailer'), ('Distributer', 'Distributer'), ('Wholeseller', 'Wholeseller'), ('Exporter', 'Exporter')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eshopeform',
            name='send_copy',
            field=models.BooleanField(default=False),
        ),
    ]
