# Generated by Django 2.2.15 on 2021-04-25 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_arrange'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='add_home',
            field=models.BooleanField(default=False),
        ),
    ]
