# Generated by Django 2.2.15 on 2021-04-22 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20210422_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='packing_details',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='video_url',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
