# Generated by Django 2.2.15 on 2021-04-28 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20210428_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eshopeform',
            name='messages',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
