# Generated by Django 2.2.15 on 2021-04-28 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20210428_1905'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EshopeForm',
        ),
    ]
