# Generated by Django 2.2.15 on 2021-04-29 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20210429_1343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='product_group',
            field=models.CharField(blank=True, choices=[('Kitchen_stoves', 'Kitchen Stoves'), ('mixture_grinder', 'Mixture Grinder'), ('rice_cookers', 'Rice Cookers'), ('food_processors', 'Food Processors'), ('electric_mixers', 'Electric Mixers'), ('juicers', 'Juicers'), ('blenders', 'Blenders'), ('water_heaters', 'Water Heaters'), ('water_filters', 'Water Filters'), ('induction cookers', 'Induction Cookers'), ('exhaust_hoods', 'Exhaust Hoods'), ('sandwich_makers', 'Sandwich Makers'), ('toaster', 'Toaster'), ('deep_fryers', 'Deep Fryers'), ('dough_blenders', 'Dough Blenders'), ('coffee_makers', 'Coffee Makers'), ('electric_iron', 'Electric Iron'), ('vaccum_cleaner', 'Vaccum Cleaner'), ('air_purifiers', 'Air Purifiers'), ('trimmers_&_savers', 'Trimmer And Savers'), ('hair_drier', 'Hair Drier')], max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
