# Generated by Django 2.2.15 on 2021-04-23 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_product_rearrange'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='rearrange',
            new_name='arrange',
        ),
    ]
