# Generated by Django 2.2.15 on 2021-04-24 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20210423_1741'),
        ('product', '0006_auto_20210423_1736'),
    ]

    operations = [
    ]
