# Generated by Django 2.2.15 on 2021-05-01 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20210430_1741'),
        ('product', '0008_auto_20210430_1526'),
    ]

    operations = [
    ]
