# Generated by Django 2.2.15 on 2021-04-25 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_merge_20210424_1202'),
        ('product', '0008_merge_20210424_0955'),
    ]

    operations = [
    ]
