# Generated by Django 2.2.15 on 2021-04-18 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_auto_20210417_1112'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promoter_first_name', models.CharField(max_length=50)),
                ('promoter_last_name', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=50)),
                ('address_building', models.CharField(max_length=100)),
                ('address_area', models.CharField(max_length=100)),
                ('landmark', models.CharField(max_length=50)),
                ('locality', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('pincode', models.CharField(max_length=50)),
                ('gstin', models.CharField(max_length=50)),
                ('company_website', models.CharField(max_length=50)),
                ('alternative_mobile', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('alternative_email', models.EmailField(max_length=50)),
                ('landline_no', models.CharField(max_length=50)),
                ('alternative_landline_no', models.CharField(max_length=50)),
                ('about_me', models.TextField()),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.Account')),
            ],
        ),
    ]
