# Generated by Django 2.2.15 on 2021-04-19 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellerstatutory',
            name='cin_no',
        ),
        migrations.RemoveField(
            model_name='sellerstatutory',
            name='company_registration_no',
        ),
        migrations.RemoveField(
            model_name='sellerstatutory',
            name='dgft_ie_code',
        ),
        migrations.RemoveField(
            model_name='sellerstatutory',
            name='gst_no',
        ),
        migrations.RemoveField(
            model_name='sellerstatutory',
            name='pan_no',
        ),
        migrations.RemoveField(
            model_name='sellerstatutory',
            name='tan_no',
        ),
    ]
