# Generated by Django 2.2.15 on 2021-04-25 10:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='images/seller_logos')),
                ('banner_image', models.ImageField(upload_to='images/seller_banner_images')),
                ('about_seller', models.TextField()),
                ('branded_video', embed_video.fields.EmbedVideoField()),
                ('catalogue', models.FileField(upload_to='files/seller_catalogues')),
                ('no_of_employees', models.PositiveIntegerField()),
                ('legal_status_of_firm', models.CharField(max_length=50)),
                ('seller_bank', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dashboard.SellerBank')),
                ('seller_business_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dashboard.BusinessProfile')),
                ('seller_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dashboard.SellerProfile')),
                ('seller_statutory', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dashboard.SellerStatutory')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
