# Generated by Django 2.2.15 on 2021-04-28 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('mobile', models.IntegerField()),
                ('business_type', models.CharField(choices=[('Manufacturer', 'Manufacturer'), ('Retailer', 'Retailer'), ('Distributer', 'Distributer'), ('Wholeseller', 'Wholeseller'), ('Exporter', 'Exporter')], max_length=20)),
                ('message', models.TextField()),
                ('send_copy', models.BooleanField(default=False)),
            ],
        ),
    ]
