# Generated by Django 2.2.15 on 2021-04-22 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessprofile',
            name='annual_turnover',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='category',
            field=models.CharField(blank=True, choices=[('Seller', 'Seller'), ('Manufacturer', 'Manufacturer')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='company_card_back_view',
            field=models.ImageField(blank=True, default='profile.png', null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='company_card_front_view',
            field=models.ImageField(blank=True, default='profile.png', null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='company_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='year_of_establishment',
            field=models.DateField(blank=True, null=True),
        ),
    ]
