# Generated by Django 2.2.15 on 2021-04-26 07:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_add_home'),
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellercompany',
            name='business_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.BusinessProfile'),
        ),
        migrations.AddField(
            model_name='sellercompany',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Product'),
        ),
        migrations.AddField(
            model_name='sellercompany',
            name='seller_bank',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.SellerBank'),
        ),
        migrations.AddField(
            model_name='sellercompany',
            name='seller_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.SellerProfile'),
        ),
        migrations.AddField(
            model_name='sellercompany',
            name='seller_statutory',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.SellerStatutory'),
        ),
        migrations.AlterField(
            model_name='sellercompany',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sellercompany', to=settings.AUTH_USER_MODEL),
        ),
    ]
