# Generated by Django 2.2.15 on 2021-04-22 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20210422_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessprofile',
            name='company_card_back_view',
            field=models.ImageField(blank=True, default='company_card.png', null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='company_card_front_view',
            field=models.ImageField(blank=True, default='company_card.png', null=True, upload_to='images/'),
        ),
    ]
