# Generated by Django 2.2.15 on 2021-04-19 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20210419_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerstatutory',
            name='cin_no',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sellerstatutory',
            name='company_registration_no',
            field=models.URLField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sellerstatutory',
            name='dgft_ie_code',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sellerstatutory',
            name='gst_no',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sellerstatutory',
            name='pan_no',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sellerstatutory',
            name='tan_no',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
