# Generated by Django 2.2.15 on 2021-04-26 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_add_home'),
        ('dashboard', '0002_auto_20210426_1251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellercompany',
            name='product',
        ),
        migrations.AddField(
            model_name='sellercompany',
            name='product',
            field=models.ManyToManyField(blank=True, null=True, to='product.Product'),
        ),
    ]
