# Generated by Django 2.2.15 on 2021-04-18 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20210418_1451'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellerprofile',
            name='email',
        ),
    ]
