# Generated by Django 2.2.15 on 2021-04-30 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_sharedetail_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sharedetail',
            name='user',
        ),
    ]
