# Generated by Django 2.2.15 on 2021-05-01 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_remove_sharedetail_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedetail',
            name='seller_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
