# Generated by Django 2.2.15 on 2021-04-26 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_sellercompany_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellercompany',
            name='product',
        ),
        migrations.RemoveField(
            model_name='sellercompany',
            name='seller_bank',
        ),
        migrations.RemoveField(
            model_name='sellercompany',
            name='seller_business_profile',
        ),
        migrations.RemoveField(
            model_name='sellercompany',
            name='seller_profile',
        ),
        migrations.RemoveField(
            model_name='sellercompany',
            name='seller_statutory',
        ),
    ]
