# Generated by Django 2.2.15 on 2021-05-01 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_sharedetail_seller_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sharedetail',
            old_name='seller_id',
            new_name='seller',
        ),
    ]
