# Generated by Django 2.2.15 on 2021-04-26 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20210426_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellercompany',
            name='about_seller',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sellercompany',
            name='banner_image',
            field=models.ImageField(default='company_card.png', upload_to='images/seller_banner_images'),
        ),
        migrations.AlterField(
            model_name='sellercompany',
            name='business_profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.BusinessProfile'),
        ),
        migrations.AlterField(
            model_name='sellercompany',
            name='catalogue',
            field=models.FileField(blank=True, null=True, upload_to='files/seller_catalogues'),
        ),
        migrations.AlterField(
            model_name='sellercompany',
            name='logo',
            field=models.ImageField(default='company_card.png', upload_to='images/seller_logos'),
        ),
        migrations.AlterField(
            model_name='sellercompany',
            name='no_of_employees',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sellercompany',
            name='seller_bank',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.SellerBank'),
        ),
        migrations.AlterField(
            model_name='sellercompany',
            name='seller_profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.SellerProfile'),
        ),
        migrations.AlterField(
            model_name='sellercompany',
            name='seller_statutory',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.SellerStatutory'),
        ),
    ]
