# Generated by Django 2.2.15 on 2021-04-18 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20210418_1556'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sellerprofile',
            old_name='pincode',
            new_name='country',
        ),
    ]
