# Generated by Django 2.2.15 on 2021-04-19 09:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0006_auto_20210418_1637'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200, null=True)),
                ('year_of_establishment', models.DateField()),
                ('phone', models.CharField(blank=True, max_length=200, null=True)),
                ('category', models.CharField(choices=[('Seller', 'Seller'), ('Manufacturer', 'Manufacturer')], max_length=200, null=True)),
                ('annual_turnover', models.DecimalField(decimal_places=2, max_digits=10)),
                ('company_card_front_view', models.FileField(blank=True, null=True, upload_to='images/')),
                ('company_card_back_view', models.FileField(blank=True, null=True, upload_to='images/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='businessprofile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
