# Generated by Django 2.2.15 on 2021-04-19 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_businessprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessprofile',
            name='year_of_establishment',
            field=models.DateField(null=True),
        ),
    ]
