# Generated by Django 2.2.15 on 2021-04-27 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20210426_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellercompany',
            name='caption',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
