# Generated by Django 2.2.15 on 2021-04-19 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20210419_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessprofile',
            name='annual_turnover',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
