# Generated by Django 2.2.15 on 2021-04-21 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20210419_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessprofile',
            name='company_card_back_view',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='company_card_front_view',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
