# Generated by Django 2.2.15 on 2021-04-17 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='category',
        ),
        migrations.RemoveField(
            model_name='account',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='account',
            name='mother_tongue',
        ),
        migrations.RemoveField(
            model_name='account',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='account',
            name='slug',
        ),
        migrations.AddField(
            model_name='account',
            name='business_type',
            field=models.CharField(choices=[('Seller', 'Seller'), ('Buye', 'Buye'), ('Logistic_Advertisement', 'Logistic Advertisement')], default='1', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='company_name',
            field=models.CharField(default='1', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='nature_of_business',
            field=models.CharField(choices=[('Manufacturer', 'Manufacturer'), ('Retailer', 'Retailer'), ('Distributer', 'Distributer'), ('Wholeseller', 'Wholeseller'), ('Exporter', 'Exporter')], default='1', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='pincode',
            field=models.CharField(default='1', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='state',
            field=models.CharField(default='1', max_length=20),
            preserve_default=False,
        ),
    ]
