# Generated by Django 2.2.15 on 2021-04-28 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210428_1314'),
        ('accounts', '0005_profilepicture_about_me'),
    ]

    operations = [
    ]
